### ISSUE TITLE
Interlaced Bug

### ISSUE THREAD

**Issue by AverageUnknown** [HomeOfAviSynthPlusEvolution/MiniDeen#1]
Using : https://raw.githubusercontent.com/realfinder/AVS-Stuff/Community/avs%202.5%20and%20up/DFMDeRainbow.avsi

with neo_minideen R9 

Getting a interlaced bug

Script: 

```
MPEG2Source("003.d2v")

DFMDeRainbow(maskthresh=10,mask=false,interlaced=true)

AnimeIVTC(mode=4,precision=4,mChroma=false,chroma=false,omode=2,pass=1,MI=100)
```
![image](https://user-images.githubusercontent.com/25883052/83365630-6ed61a80-a35e-11ea-8ff0-e0daeb10612f.png)

another script:

```
SeparateFields()
minideen()
Weave()
```

**Comment by msg7086** [comment]
Please try r10

**Comment by AverageUnknown** [comment]
Fixed ty.
