### ISSUE TITLE
AVS preview not working with minideen

### ISSUE THREAD

**Issue by ghost** [HomeOfAviSynthPlusEvolution/MiniDeen#3]
When I open with any player an avs file to watch the preview I get a system exception - access violation. Can you verify if it's the filter or it is just me? Thanks.

**Comment by kedaitinh12** [comment]
Maybe your issue relate vc++. Here for latest ver
https://github.com/abbodi1406/vcredist/releases

**Comment by ghost** [comment]
Didn't work. Can you link a player that works for you?

**Comment by kedaitinh12** [comment]
I use normally to watch the preview with Megui x64
